# Assignment 2 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [1]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [19]:
dir_path = r'C:\Users\World\Desktop\Machine Learning\Assignment\Asssignment 02\myfile'
for filename in os.listdir(dir_path):
    full_path = os.path.join(dir_path,filename) #to get fullpath
    if os.path.isfile(full_path): #check if each file in dir is a file
        file_count +=1
        with open(full_path,'r') as file:
            first_line = file.readline()
            words = first_line.split()
            length = len(words)
            files_dict[filename] = length
print("Dictionary Containing file: ",files_dict)
print("Total File Count: ",file_count)
            

Dictionary Containing file:  {'f1.txt': 7, 'f2.txt': 5, 'f3.txt': 6}
Total File Count:  9


In [20]:
# Here we have intialized some variables, you can add more if required.

file_count = 3          # file_count to count number of files
files_dict = {'f1.txt': 7, 'f2.txt': 5, 'f3.txt': 6}           # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


Displaying the count of files.

In [21]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [22]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 7, 'f2.txt': 5, 'f3.txt': 6}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [23]:
#Your code starts here   

print("\nUnique words in every file: ")
for filename in os.listdir(dir_path):
    with open(full_path,'r') as file:
        words = file.read().split()
        unique_word_set.update(words)
print(unique_word_set)
print("Count of file: ",file_count)
            
#Your code ends here


Unique words in every file: 
{'of', 'Exploring', 'Rainforest', 'the', 'Wonders'}
Count of file:  3


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

- Create Term doc matrix such that colmns will be unique words and all the files will be rows
- Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [24]:
#Your code starts here    
print("Count of unique words: ", len(unique_word_set))
unique_words_dict = {word: index for index, word in enumerate(unique_word_set)}
files_index_dict = {filename: index for index, filename in enumerate(files_dict.keys())}
print("Dictionary of Unique words: ")
print(unique_words_dict)

print("\nDictionary of Files: ")
print(files_index_dict)
term_doc_matrix = np.zeros((len(files_index_dict), len(unique_words_dict)),dtype=int)
print(term_doc_matrix)

        
        


#Your code ends here

Count of unique words:  5
Dictionary of Unique words: 
{'of': 0, 'Exploring': 1, 'Rainforest': 2, 'the': 3, 'Wonders': 4}

Dictionary of Files: 
{'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

- Fill the term doc matrix by checking if the unique word exists in a file or not
- If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
- Do the same for all the files present in the directory

In [28]:
#Your code starts here    
term_doc_matrix = {}
for filename, path in files_dict.items():
    term_doc_matrix[filename] = {}
    with open(full_path,'r') as file:
        words = set(file.read().split(','))
        for word in unique_word_set:
            if word in words:
                term_doc_matrix[filename][word] = 1 
print("Term-Document Matrix:")
for filename, word_counts in term_doc_matrix.items():
    print(filename)
    for word, count in word_counts.items():
            print(f"\t{words}: {file_count}")
                



#Your code ends here!!!!!!!!!!!!!!!!!!!!!!ASk!!!!!!!!!!!!!!

Term-Document Matrix:
f1.txt
f2.txt
f3.txt


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [29]:
#Your code starts here    
user_query = {'of': 0, 'Exploring': 1, 'Rainforest': 2, 'the': 3, 'Wonders': 4}
user_query_vector = np.zeros(len(unique_word_set))
for i, word in enumerate(unique_word_set):
    if word in user_query:
        user_query_vector[i] = 1
print("User query vector: ",user_query_vector)
#Your code ends here

User query vector:  [1. 1. 1. 1. 1.]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [33]:
query = input("The Amazing Tale of a Tiny Dog")
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary
word_dict = {'of': 0, 'Rainforest': 1, 'the': 2, 'Wonders': 3, 'Exploring': 4}

for word in query:
    if word in unique_word_set:
        if word in word_dict:
            word_dict[word] += 1
        else:
            word_dict[word] =1



### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [1]:
#Your code starts here  
prod = np.dot(term_doc_matrix, resultant_vector)
print(prod)

max_val = np.max(prod)
max_index = np.argmax(prod)

print("Max Value: ",max_val)
print("Max Index: ", max_index)

#Your code ends here

NameError: name 'np' is not defined

### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [ ]:
#Your code starts here    

max_file_index = np.argmax(resultant_vector)
max_filename = list(files_dict.keys())[max_file_index]
print("Filename with max value in resultant vector: ", max_filename)
max_file_path = files_dict[max_filename]

with open(full_path, 'r') as file:
    file_contents = file.read()
    print("contents of file: ")
    print(file_contents)


#Your code ends here

Congratulations Now you are able to build your own small IRS.